artifact_uri: file:///D:/DICODING%20x%20PIJAK/SUBMISSION/MEMBANGUN%20SISTEM%20MACHINE%20LEARNING/Eksperimen_SML_Ahmad_Fauzul_Adhim/preprocessing/mlflow_artifacts/513228651688362952/b93812e32acc411694a6708c8a7f127c/artifacts
end_time: 1780556752019
entry_point_name: ''
experiment_id: '513228651688362952'
lifecycle_stage: active
run_id: b93812e32acc411694a6708c8a7f127c
run_name: RF_GridSearchCV_Best
source_name: ''
source_type: 4
source_version: ''
start_time: 1780556716706
status: 3
tags: []
user_id: Adhim
