artifact_uri: file:///d:/DICODING x PIJAK/SUBMISSION/MEMBANGUN SISTEM MACHINE LEARNING/Eksperimen_SML_Ahmad_Fauzul_Adhim/tracking_uri/911439305545115146/9902bfb773f14a2d9c17a92ae5aad501/artifacts
end_time: 1780564987231
entry_point_name: ''
experiment_id: '911439305545115146'
lifecycle_stage: active
run_id: 9902bfb773f14a2d9c17a92ae5aad501
run_name: RandomForest_Autolog
source_name: ''
source_type: 4
source_version: ''
start_time: 1780564965070
status: 3
tags: []
user_id: Adhim
