artifact_location: file:///d:/DICODING x PIJAK/SUBMISSION/MEMBANGUN SISTEM MACHINE
  LEARNING/Eksperimen_SML_Ahmad_Fauzul_Adhim/tracking_uri/911439305545115146/models/m-a0c87c9809f04bd9acdf71bf00b6cd92/artifacts
creation_timestamp: 1780564965785
experiment_id: '911439305545115146'
last_updated_timestamp: 1780564981221
model_id: m-a0c87c9809f04bd9acdf71bf00b6cd92
model_type: null
name: model
source_run_id: 9902bfb773f14a2d9c17a92ae5aad501
status: 2
status_message: null
