artifact_location: file:///d:/DICODING x PIJAK/SUBMISSION/MEMBANGUN SISTEM MACHINE
  LEARNING/Eksperimen_SML_Ahmad_Fauzul_Adhim/tracking_uri/911439305545115146
creation_time: 1780564962107
experiment_id: '911439305545115146'
last_update_time: 1780564962107
lifecycle_stage: active
name: Heart-Failure-Prediction
trace_location: null
workspace: default
