name: Preprocessing Pipeline

on:
  push:
    branches: [ master ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  preprocessing:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11.9"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas numpy scikit-learn matplotlib seaborn

      - name: Run preprocessing
        run: |
          cd preprocessing
          python automate_Ahmad-Fauzul-Adhim.py

      - name: Upload preprocessed dataset
        uses: actions/upload-artifact@v4
        with:
          name: preprocessed-dataset
          path: preprocessing/heartfailure_preprocessing.csv

      - name: Commit preprocessed data
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add preprocessing/heartfailure_preprocessing.csv
          git diff --cached --quiet || git commit -m "Auto: Update Heart Failure preprocessed dataset from preprocessing pipeline"
          git push

      - name: Show Repository Structure
        run: |
          pwd
          ls -la
          find . -type f
